#!/usr/bin/env bash
# =====================================================================
#  deploy.sh  –  One-command build & deploy for STCPOC on Hercules
#
#  Generates a single JCL job that:
#    1. Loads local .asm source into MVS PDSes via IEBUPDTE
#    2. Assembles and link-edits STCMAIN and STCCLNT
#  Then (optionally) restarts the started task and runs the test job.
#
#  Usage:
#    ./deploy.sh               # stop STC → build → start STC
#    ./deploy.sh --build-only  # build only, don't touch the STC
#    ./deploy.sh --test        # full cycle + submit STCTEST.JCL
#    ./deploy.sh --jcl-only    # just write the JCL file, don't submit
#
#  All tunables can be overridden via environment variables.
# =====================================================================

# ── Configuration ────────────────────────────────────────────────
# Hercules HTTP console URL (TK4- default is 8038; Hyperion often 8081)
HERC_URL="${HERC_URL:-http://localhost:8038}"

# Card reader device address
CARD_DEV="${CARD_DEV:-00c}"

# Started task name
STC_NAME="${STC_NAME:-STCPOC}"

# Seconds to wait for the build job to finish before restarting the STC
BUILD_WAIT="${BUILD_WAIT:-5}"

# ── Paths ────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

SRC_MAIN="${SCRIPT_DIR}/STCMAIN.asm"
SRC_CLNT="${SCRIPT_DIR}/STCCLNT.asm"
SRC_REQ="${SCRIPT_DIR}/STCREQ.asm"
SRC_DSECT="${SCRIPT_DIR}/STCDSECT.asm"
SRC_RQPB="${SCRIPT_DIR}/STCRQPB.asm"

# Output JCL written here (must be readable by Hercules).
JCL_FILE="${SCRIPT_DIR}/_deploy.jcl"

# Hercules runs as a native Windows process, so it needs Windows-style
# paths.  Auto-convert if running in Git Bash / MSYS2.
if command -v cygpath &>/dev/null; then
    HERC_JCL_PATH="${HERC_JCL_PATH:-$(cygpath -m "$JCL_FILE")}"
else
    HERC_JCL_PATH="${HERC_JCL_PATH:-${JCL_FILE}}"
fi

# ── Helpers ──────────────────────────────────────────────────────
info() { printf '>>> %s\n' "$*"; }
warn() { printf 'WARNING: %s\n' "$*" >&2; }
die()  { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

# Send a command to the Hercules console via its HTTP interface.
herc_cmd() {
    if ! MSYS_NO_PATHCONV=1 curl -sf --max-time 5 \
            "${HERC_URL}/cgi-bin/tasks/syslog" \
            --data-urlencode "command=$1" >/dev/null 2>&1; then
        warn "Could not send to Hercules (${HERC_URL}): $1"
        return 1
    fi
}

# Send an MVS operator command (routed through Hercules).
mvs_cmd() { herc_cmd "/ $1"; }

# Emit one PDS member for IEBUPDTE: control card + source lines.
# Strips Windows CR, truncates to 80 cols (Hercules pads short lines).
emit_member() {
    local name="$1" file="$2"
    printf './ ADD NAME=%s,LIST=ALL\n' "$name"
    sed 's/\r$//' "$file" | cut -c1-80
}

# ── JCL Generation ──────────────────────────────────────────────
generate_jcl() {
    # ── JOB card (no NOTIFY – not submitted through TSO) ─────────
    cat <<EOF
//STCBLD  JOB (ACCT),'DEPLOY STCPOC',CLASS=A,MSGCLASS=X,
//         MSGLEVEL=(1,1),NOTIFY=$MVS_USERID,
//         USER=$MVS_USERID,PASSWORD=$MVS_PASSWORD
//*  Generated by deploy.sh  $(date '+%Y-%m-%d %H:%M:%S')
//*
EOF

    # ── IEBUPDTE: load STCMAIN, STCCLNT, STCDSECT into SRCLIB ───
    cat <<'JCL'
//*--------------------------------------------------------------------
//*  Upload source into STCPOC.SRCLIB
//*--------------------------------------------------------------------
//UPDSRC  EXEC PGM=IEBUPDTE,PARM=NEW
//SYSPRINT DD  SYSOUT=*
//SYSUT2   DD  DSN=STCPOC.SRCLIB,DISP=SHR
//SYSIN    DD  DATA,DLM=@@
JCL
    emit_member "STCMAIN"  "$SRC_MAIN"
    emit_member "STCCLNT"  "$SRC_CLNT"
    emit_member "STCREQ"   "$SRC_REQ"
    emit_member "STCDSECT" "$SRC_DSECT"
    emit_member "STCRQPB"  "$SRC_RQPB"
    printf './ ENDUP\n'
    printf '@@\n'

    # ── IEBUPDTE: load STCDSECT into MACLIB (COPY member) ────────
    cat <<'JCL'
//*--------------------------------------------------------------------
//*  Upload STCDSECT into STCPOC.MACLIB  (assembler COPY member)
//*--------------------------------------------------------------------
//UPDMAC  EXEC PGM=IEBUPDTE,PARM=NEW
//SYSPRINT DD  SYSOUT=*
//SYSUT2   DD  DSN=STCPOC.MACLIB,DISP=SHR
//SYSIN    DD  DATA,DLM=@@
JCL
    emit_member "STCDSECT" "$SRC_DSECT"
    emit_member "STCRQPB"  "$SRC_RQPB"
    printf './ ENDUP\n'
    printf '@@\n'

    # ── Assemble + Link-edit ─────────────────────────────────────
    cat <<'JCL'
//*--------------------------------------------------------------------
//*  Assemble STCMAIN
//*--------------------------------------------------------------------
//ASMSTC  EXEC PGM=IFOX00,REGION=512K,
//             PARM='OBJECT,NODECK,LIST,NOXREF'
//SYSPRINT DD  SYSOUT=*
//SYSUT1   DD  UNIT=SYSDA,SPACE=(CYL,(1,1))
//SYSUT2   DD  UNIT=SYSDA,SPACE=(CYL,(1,1))
//SYSUT3   DD  UNIT=SYSDA,SPACE=(CYL,(1,1))
//SYSLIB   DD  DSN=STCPOC.MACLIB,DISP=SHR,
//             DCB=BLKSIZE=32760
//         DD  DSN=SYS2.MACLIB,DISP=SHR
//         DD  DSN=SYS1.MACLIB,DISP=SHR
//         DD  DSN=SYS1.AMODGEN,DISP=SHR
//SYSIN    DD  DSN=STCPOC.SRCLIB(STCMAIN),DISP=SHR
//SYSGO    DD  DSN=&&STCOBJ,UNIT=SYSDA,SPACE=(CYL,(1,1)),
//             DISP=(NEW,PASS)
//*--------------------------------------------------------------------
//*  Link-edit STCMAIN  (SETCODE AC=1 for APF)
//*--------------------------------------------------------------------
//LNKSTC  EXEC PGM=IEWL,REGION=512K,COND=(0,LT,ASMSTC),
//             PARM='LIST,XREF,LET,NORENT,REFR'
//SYSPRINT DD  SYSOUT=*
//SYSUT1   DD  UNIT=SYSDA,SPACE=(CYL,(1,1))
//SYSLIN   DD  DSN=&&STCOBJ,DISP=(OLD,DELETE)
//         DD  *
  SETCODE AC(1)
  NAME STCMAIN(R)
/*
//SYSLMOD  DD  DSN=STCPOC.LOADLIB,DISP=SHR
//*--------------------------------------------------------------------
//*  Assemble STCCLNT
//*--------------------------------------------------------------------
//ASMCLNT EXEC PGM=IFOX00,REGION=512K,
//             PARM='OBJECT,NODECK,LIST,NOXREF',
//             COND=(0,LT,LNKSTC)
//SYSPRINT DD  SYSOUT=*
//SYSUT1   DD  UNIT=SYSDA,SPACE=(CYL,(1,1))
//SYSUT2   DD  UNIT=SYSDA,SPACE=(CYL,(1,1))
//SYSUT3   DD  UNIT=SYSDA,SPACE=(CYL,(1,1))
//SYSLIB   DD  DSN=STCPOC.MACLIB,DISP=SHR,
//             DCB=BLKSIZE=32760
//         DD  DSN=SYS2.MACLIB,DISP=SHR
//         DD  DSN=SYS1.MACLIB,DISP=SHR
//         DD  DSN=SYS1.AMODGEN,DISP=SHR
//SYSIN    DD  DSN=STCPOC.SRCLIB(STCCLNT),DISP=SHR
//SYSGO    DD  DSN=&&CLNOBJ,UNIT=SYSDA,SPACE=(CYL,(1,1)),
//             DISP=(NEW,PASS)
//*--------------------------------------------------------------------
//*  Assemble STCREQ (IPC module)
//*--------------------------------------------------------------------
//ASMREQ  EXEC PGM=IFOX00,REGION=512K,
//             PARM='OBJECT,NODECK,LIST,NOXREF',
//             COND=(0,LT,ASMCLNT)
//SYSPRINT DD  SYSOUT=*
//SYSUT1   DD  UNIT=SYSDA,SPACE=(CYL,(1,1))
//SYSUT2   DD  UNIT=SYSDA,SPACE=(CYL,(1,1))
//SYSUT3   DD  UNIT=SYSDA,SPACE=(CYL,(1,1))
//SYSLIB   DD  DSN=STCPOC.MACLIB,DISP=SHR,
//             DCB=BLKSIZE=32760
//         DD  DSN=SYS2.MACLIB,DISP=SHR
//         DD  DSN=SYS1.MACLIB,DISP=SHR
//         DD  DSN=SYS1.AMODGEN,DISP=SHR
//SYSIN    DD  DSN=STCPOC.SRCLIB(STCREQ),DISP=SHR
//SYSGO    DD  DSN=&&REQOBJ,UNIT=SYSDA,SPACE=(CYL,(1,1)),
//             DISP=(NEW,PASS)
//*--------------------------------------------------------------------
//*  Link-edit STCCLNT + STCREQ into single load module
//*--------------------------------------------------------------------
//LNKCLNT EXEC PGM=IEWL,REGION=512K,COND=(0,LT,ASMREQ),
//             PARM='LIST,XREF,LET,NORENT,REFR'
//SYSPRINT DD  SYSOUT=*
//SYSUT1   DD  UNIT=SYSDA,SPACE=(CYL,(1,1))
//SYSLIN   DD  DSN=&&CLNOBJ,DISP=(OLD,DELETE)
//         DD  DSN=&&REQOBJ,DISP=(OLD,DELETE)
//         DD  *
  SETCODE AC(1)
  NAME STCCLNT(R)
/*
//SYSLMOD  DD  DSN=STCPOC.LOADLIB,DISP=SHR
//
JCL
}

# ── Argument parsing ─────────────────────────────────────────────
BUILD_ONLY=false
JCL_ONLY=false
RUN_TEST=false

for arg in "$@"; do
    case "$arg" in
        --build-only) BUILD_ONLY=true ;;
        --jcl-only)   JCL_ONLY=true ;;
        --test)       RUN_TEST=true ;;
        -h|--help)
            cat <<USAGE
Usage: $(basename "$0") [OPTIONS]

Options:
  --build-only   Upload source and build; do not stop/start the STC
  --jcl-only     Generate _deploy.jcl only; do not submit to Hercules
  --test         After restart, also submit STCTEST.JCL
  -h, --help     Show this help

Environment variables (override defaults):
  HERC_URL         Hercules HTTP console URL   [${HERC_URL}]
  CARD_DEV         Card reader device address   [${CARD_DEV}]
  STC_NAME         Started task name            [${STC_NAME}]
  BUILD_WAIT       Seconds to wait for build    [${BUILD_WAIT}]
  HERC_JCL_PATH    JCL path as seen by Hercules [${HERC_JCL_PATH}]
USAGE
            exit 0
            ;;
        *) die "Unknown option: $arg  (try --help)" ;;
    esac
done

# ── Preflight ────────────────────────────────────────────────────
for f in "$SRC_MAIN" "$SRC_CLNT" "$SRC_REQ" "$SRC_DSECT" "$SRC_RQPB"; do
    [[ -f "$f" ]] || die "Source file not found: $f"
done

# ── Generate the JCL ─────────────────────────────────────────────
info "Generating deploy JCL -> ${JCL_FILE}"
generate_jcl > "$JCL_FILE"

if $JCL_ONLY; then
    info "Done (--jcl-only).  Submit manually:"
    info "  devinit ${CARD_DEV} ${HERC_JCL_PATH}"
    exit 0
fi

# ── Stop the STC (unless --build-only) ───────────────────────────
if ! $BUILD_ONLY; then
    info "Stopping ${STC_NAME}..."
    mvs_cmd "P ${STC_NAME}" || true
    sleep 3
fi

# ── Submit via Hercules card reader ──────────────────────────────
info "Submitting build job via card reader (${CARD_DEV})..."
if ! herc_cmd "devinit ${CARD_DEV} ${HERC_JCL_PATH} ascii eof"; then
    warn "Auto-submit failed.  Run on Hercules console:"
    warn "  devinit ${CARD_DEV} ${HERC_JCL_PATH} ascii eof"
fi

info "Waiting ${BUILD_WAIT}s for build to complete..."
sleep "$BUILD_WAIT"

# ── Start the STC (unless --build-only) ──────────────────────────
if ! $BUILD_ONLY; then
    info "Starting ${STC_NAME}..."
    mvs_cmd "S ${STC_NAME}" || true
    sleep 2
fi

# ── Optional: submit test job ────────────────────────────────────
if $RUN_TEST; then
    TEST_JCL_FILE="${SCRIPT_DIR}/_test.jcl"
    info "Generating test JCL -> ${TEST_JCL_FILE}"
    cat <<EOF > "$TEST_JCL_FILE"
//STCTEST  JOB (ACCT),'TEST STCPOC CLIENT',CLASS=A,MSGCLASS=X,
//             MSGLEVEL=(1,1),NOTIFY=$MVS_USERID,
//             USER=$MVS_USERID,PASSWORD=$MVS_PASSWORD
EOF
    # Append everything after the JOB card (lines 1-2) from STCTEST.JCL
    sed 's/\r$//' "${SCRIPT_DIR}/STCTEST.JCL" | tail -n +3 >> "$TEST_JCL_FILE"

    if command -v cygpath &>/dev/null; then
        TEST_HERC_PATH="$(cygpath -m "$TEST_JCL_FILE")"
    else
        TEST_HERC_PATH="$TEST_JCL_FILE"
    fi
    info "Submitting test job -> ${TEST_HERC_PATH}"
    herc_cmd "devinit ${CARD_DEV} ${TEST_HERC_PATH} ascii eof" || true
fi

info "Done.  Check SYSLOG / JES2 output for job results."
